[build]
  base = "client"
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "client/build"

[build.processing]
  skip_processing = true

[build.processing.html]
  pretty_urls = false